amagid/Game-Development-Fall-2018

- Assets/Scripts/SwitchController.cs
> chore(test): testing git still not sure whats happening

- Assets/Scenes/TestScene1.unity
Got rid of the skybox, added a source light to the player, and made the player have tunnel vision.
> feat(lightDark):Made the room dark, tunnel vision

- Assets/Scenes/TestScene1.unity
- Assets/Scripts/DoorController.cs
- Assets/Scripts/SwitchController.cs
Door would only work in the x axis direction. Made doors and switches have a direct reference to each other and an indicator of what axis they should move to open and close
> feat(door+switch): made doors and switches abstract

- Assets/Scripts/PlayerCharacter.cs
UI message should be shown on all screen sizes so cannot be hard coded.
> <fix> UI message does on different screen set

- Assets/Scenes/TestScene1.unity
- Assets/Scripts/DoorController.cs
- Assets/Scripts/PlayerCharacter.cs
- Assets/Scripts/SwitchController.cs
- ProjectSettings/ProjectVersion.txt
sanity stops decreasing after player obtains a battery and previous compilation errors fixed
> feat(sanityStop):playerHasBatterSanityStops

- Assets/Models.meta
- Assets/Models/battery.fbx
- Assets/Models/battery.fbx.meta
- Assets/Scenes/TestScene1.unity
I also created an additional battery object at the start of the level to test its functionality.
> asset(Battery): Added Battery asset.

- Assets/Scenes/TestScene1.unity
Added point lights to the asset battery
> fix(battery error):added point lights to asset battery

- Assets/Scenes/TestScene1.unity
The player cannot be near a wall and see through it to the other side.
> fix(player can see through walls): camera fixed

- Assets/Backstory Clues/Note_1.jpg
- Assets/Scenes/TestScene1.unity
- Assets/Scripts/NoteController.cs
- Assets/Scripts/PlayerCharacter.cs
The NoteController script can now be attached to a game object and once the appropriate gameobjects and images are dragged into it, it will display the image to the player when the player presses the E key. You also need to make sure the collider attached to the interactable game object is big enough so that the player can trigger the call.
> feat(abstractNoteController):notecontroller is abstract

- Assets/Backstory Clues/ResourceLog.jpg
- Assets/Backstory Clues/ResourceLog.jpg.meta
- Assets/Backstory Clues/Schematic.jpg
- Assets/Backstory Clues/Schematic.jpg.meta
- Assets/Scenes/TestScene1.unity
- Assets/Scripts/NoteController.cs
Note placed in Zone 3, changed the image for note in zone 2
> feat(moreBackStoryClues): added more notes in the zones

- Assets/Scenes/TestScene1.meta
- Assets/Scenes/TestScene1.unity
- Assets/Scripts/InventoryUI.cs
redeisgn the ui
add the inventory shortcut in the game
> Re-design UI

- Assets/Scenes/TestScene1.unity
- Assets/Scripts/Inventory.cs
- Assets/Scripts/InventoryUI.cs
- Assets/Scripts/PlayerCharacter.cs
Reverts amagid/Game-Development-Fall-2018#71
> Revert "<Feat> Implement battery selection"

- Assets/Scenes/TestScene1.unity
- Assets/Scripts/Inventory.cs
- Assets/Scripts/InventoryUI.cs
- Assets/Scripts/PlayerCharacter.cs
Reverts amagid/Game-Development-Fall-2018#83
> Revert "Battery selection"

- Assets/Scripts/InventoryUI.cs
Fix the null reference in tablet UI when click the charge and discharge. Charge and discharge can work properly now.
> FixedTabletUI

- Assets/Scenes/TestScene1.unity
> Fix the open and close tablet

- Assets/Scenes/TestScene1.unity
- Assets/Scripts/MazeController.cs
- Assets/Scripts/MazeDoorSwitch.cs
Reverts amagid/Game-Development-Fall-2018#96
> Revert "Feature/level2 maze switch"

- Assets/Scenes/TestScene1.unity
- Assets/Scripts/ComputerController.cs
- Assets/Scripts/SceneController.cs
also deleted the SecondaryCameraGO since not using that to pause the game
> fix(pauseGame):script not enabled when unpausing game

- Assets/Inventory pieces.meta
- Assets/Inventory pieces/invintory_UI_Alternate_Inventory_Tab.png
- Assets/Inventory pieces/invintory_UI_Alternate_Inventory_Tab.png.meta
- Assets/Inventory pieces/invintory_UI_Plain_Inventory_Tab.png
- Assets/Inventory pieces/invintory_UI_Plain_Inventory_Tab.png.meta
- Assets/Inventory pieces/invintory_UI_Plain_Notes_tab.png
- Assets/Inventory pieces/invintory_UI_Plain_Notes_tab.png.meta
- Assets/Inventory pieces/invintory_UI_cubes.png
- Assets/Inventory pieces/invintory_UI_cubes.png.meta
- Assets/Inventory pieces/invintory_UI_power_bar.png
- Assets/Inventory pieces/invintory_UI_power_bar.png.meta
- Assets/Inventory pieces/invintory_UI_single_cube.png
- Assets/Inventory pieces/invintory_UI_single_cube.png.meta
- Assets/Scenes/TestScene1.unity
> Add asset to tablet

- Assets/Inventory pieces/invintory_UI_power_bar_body.png
- Assets/Inventory pieces/invintory_UI_power_bar_body.png.meta
- Assets/Scenes/TestScene1.meta
Add the character like power bar
> Add the power bar

- Assets/AudioClips.meta
- Assets/Scripts/MachineController.cs
- Assets/Scripts/MachinePartController.cs
- Assets/Scripts/MachinePartController.cs.meta
- Assets/Scripts/MachinePartPosition.cs
- Assets/Scripts/MachinePartPosition.cs.meta
- Assets/Scripts/PlayerCharacter.cs
Mostly just adding new files, shouldn't change anything just adding the functionality for the machine parts. Will need to update the scene once this is implemented
> scripts for the machine parts to work

- Assets/Scenes/MainMenu.unity
- Assets/Scenes/TestScene1.unity
- Assets/UI/PauseMenu.meta
- Assets/UI/PauseMenu/Exit.png
- Assets/UI/PauseMenu/Exit.png.meta
- Assets/UI/PauseMenu/help.png
- Assets/UI/PauseMenu/help.png.meta
- Assets/UI/PauseMenu/resstart.png
- Assets/UI/PauseMenu/resstart.png.meta
- Assets/UI/PauseMenu/resume.png
- Assets/UI/PauseMenu/resume.png.meta
1. Pause Menu assets added.
2. Make the character power bar less transparent
> PauseMenuAssets

- Assets/Scenes/TestScene1.unity
UI anchor alignment
Add the asset of open note button
> UI anchor reset

- Assets/Scenes/TestScene1.unity
- Assets/Scripts/InventoryUI.cs
- Assets/Scripts/NoteController.cs
- Assets/Scripts/TabletUI.cs
- Clickable selection in UI
- Fixed bug where cursor not showing when note is opened by inventory
- Resume tablet after note is closed
- fixed dangling charge/drain
> <fix> Clickable selection in UI/cursor showing with note/resume tablet

- Assets/Scenes/TestScene1.unity
replaced all placeholder batteries with battery art asset
> fix(updatedBatteryPrefabs)

- Assets/Main Menu Pieces/opening-screen_0001_Rectangle-1.png
- Assets/Main Menu Pieces/opening-screen_0001_Rectangle-1.png.meta
- Assets/Scenes/MainMenu.unity
Add the rectangle selector on button
> Add the rectangle selector on button

- Assets/Scenes/TestScene1.unity
- Assets/Scripts/Inventory.cs
- Assets/Scripts/InventoryUI.cs
selects the battery with the most power when adding or removing
> feat(selectMaxBatteryAddingRemoving)
